name: Node.js CI

 push:
    branches:
      - my-new-branch
      - branch-two
  pull_request:
    branches:
      - my-new-branch

jobs:
   tests:
      runs-on: unbuntu-latest


      strategy:
        matrix:
          node-version: [16.x, 20.x]

      steps:
          -uses: actions/checkout@v2
          -name: Use Node.js ${{ matrix.node-version}}
           uses: actions/setup-node@v1
           with:
              node-version: ${{matrix.node-version}}

              -name: npm install
               run: npm ci
              -name: tests
               run: npm test 

          
